topics = {
    "science": {
        "biology": {
            "link": "https://quizlet.com/gb/topic/science/biology/{}/",
            "topics": ["anatomy",
                       "animal-science",
                       "biochemistry",
                       "bioinformatics",
                       "biophysics",
                       "biotechnology",
                       "botany",
                       "cell-biology",
                       "developmental-biology",
                       "ecology",
                       "evolutionary-biology",
                       "genetics",
                       "histology",
                       "human-biology",
                       "immunology",
                       "life-science",
                       "marine-biology",
                       "microbiology",
                       "molecular-biology",
                       "mycology",
                       "neuroscience",
                       "parasitology",
                       "pathology",
                       "physiology",
                       "structural-biology",
                       "systematics",
                       "virology",
                       "zoology"]
        },
        "chemistry": {
            "link": "https://quizlet.com/gb/topic/science/chemistry/{}/",
            "topics": ["acids-and-bases",
                       "amino-acids",
                       "analytical-chemistry",
                       "atmospheric-chemistry",
                       "biological-chemistry",
                       "environmental-chemistry",
                       "food-chemistry",
                       "green-chemistry",
                       "histochemistry",
                       "inorganic-chemistry",
                       "marine-chemistry",
                       "medicinal-chemistry",
                       "neurochemistry",
                       "nuclear-chemistry",
                       "oenology",
                       "organic-chemistry",
                       "organometallic-chemistry",
                       "periodic-table-of-elements",
                       "photochemistry",
                       "physical-chemistry",
                       "polyatomic-ions",
                       "polymer-chemistry",
                       "radiochemistry",
                       "surface-chemistry",
                       "theoretical-chemistry"]
        },
        "computer science": {
            "link": "https://quizlet.com/gb/topic/science/computer-science/{}/",
            "topics": ["algorithms",
                       "artificial-intelligence",
                       "computational-theory",
                       "computer-architecture",
                       "computer-graphics",
                       "computer-networks",
                       "computer-security-and-reliability",
                       "data-structures",
                       "databases",
                       "distributed-computing",
                       "history-of-computer-science",
                       "information-architecture",
                       "operating-systems",
                       "parallel-computing",
                       "programming-languages",
                       "software-engineering"]
        },
        "earth science": {
            "link": "https://quizlet.com/gb/topic/science/earth-science/{}/",
            "topics": ["biogeography",
                       "cartography",
                       "climatology",
                       "environmental-science",
                       "gemology",
                       "geobiology",
                       "geology",
                       "geomatics",
                       "geophysics",
                       "glaciology",
                       "hydrology",
                       "oceanography",
                       "paleontology",
                       "pedology"]
        },
        "engineering": {
            "link": "https://quizlet.com/gb/topic/science/engineering/{}/",
            "topics": ["chemical-engineering",
                       "civil-engineering",
                       "educational-technology",
                       "electrical-engineering",
                       "materials-science",
                       "mechanical-engineering",
                       "systems-theory"]
        },
        "medicine": {
            "link": "https://quizlet.com/gb/topic/science/medicine/{}/",
            "topics": ["alternative-medicine",
                       "cardiology",
                       "clinical-laboratory-sciences",
                       "dentistry",
                       "dermatology",
                       "emergency-medicine",
                       "gastroenterology",
                       "geriatrics",
                       "gynaecology",
                       "health-computing",
                       "hematology",
                       "hepatology",
                       "infectious-disease",
                       "toxicology",
                       "music-therapy",
                       "nephrology",
                       "neurology",
                       "nursing",
                       "nutrition",
                       "obstetrics",
                       "occupational-therapy",
                       "occupational-toxicology",
                       "oncology",
                       "ophthalmology",
                       "optometry",
                       "otolaryngology",
                       "pathophysiology",
                       "paediatrics",
                       "pharmaceutical-sciences",
                       "physical-fitness",
                       "physical-therapy",
                       "physiotherapy",
                       "podiatry",
                       "preventive-medicine",
                       "primary-care",
                       "psychiatry",
                       "public-health",
                       "pulmonology",
                       "radiology",
                       "rheumatology",
                       "surgery",
                       "traditional-medicine",
                       "urology",
                       "veterinary-medicine"]
        },
        "physics": {
            "link": "https://quizlet.com/gb/topic/science/physics/{}/",
            "topics": ["acoustics",
                       "applied-physics",
                       "atmospheric-physics",
                       "biomechanics",
                       "classical-mechanics",
                       "electromagnetism",
                       "fluid-dynamics",
                       "optical-physics",
                       "particle-physics",
                       "quantum-mechanics",
                       "relativity",
                       "thermodynamics"]
        },
        "space science": {
            "link": "https://quizlet.com/gb/topic/science/space-science/{}/",
            "topics": ["astrobiology",
                       "astronomy"]
        },
    },

    "math": {
        "algebra": {
            "link": "https://quizlet.com/gb/topic/math/algebra/{}/",
            "topics": ["abstract-algebra",
                       "group-theory",
                       "linear-algebra",
                       "number-theory",
                       "pre-algebra"]
        },
        "applied math": {
            "link": "https://quizlet.com/gb/topic/math/applied-math/{}/",
            "topics": ["decision-analysis",
                       "dynamic-programming",
                       "dynamic-systems",
                       "game-theory",
                       "graph-theory",
                       "information-theory",
                       "linear-programming",
                       "numerical-analysis",
                       "systems-analysis"]
        },
        "arithmetic": {
            "link": "https://quizlet.com/gb/topic/math/arithmetic/{}/",
            "topics": ["integers",
                       "multiplication"]
        },
        "calculus": {
            "link": "https://quizlet.com/gb/topic/math/calculus/{}/",
            "topics": ["differential-equations"]
        },
        "discrete math": {
            "link": "https://quizlet.com/gb/topic/math/discrete-math/{}/",
            "topics": ["combinatorics",
                       "set-theory"]
        },
        "geometry": {
            "link": "https://quizlet.com/gb/topic/math/geometry/{}/",
            "topics": ["algebraic-geometry",
                       "topology",
                       "trigonometry"]
        },
        "mathematical foundations": {
            "link": "https://quizlet.com/gb/topic/math/mathematical-foundations/{}/",
            "topics": ["view-all"]
        },
        "mathematical analysis": {
            "link": "https://quizlet.com/gb/topic/math/mathematical-analysis/{}/",
            "topics": ["complex-analysis",
                       "fourier-analysis",
                       "real-analysis"]
        },
        "probability": {
            "link": "https://quizlet.com/gb/topic/math/probability/{}/",
            "topics": ["probability-theory"]
        },
        "statistics": {
            "link": "https://quizlet.com/gb/topic/math/statistics/{}/",
            "topics": ["hypothesis-testing"]
        }
    },

    "arts": {
        "art history": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/art-history/{}/",
            "topics": ["art-of-africa",
                       "art-of-asia",
                       "art-of-europe",
                       "art-of-oceania",
                       "baroque-art",
                       "contemporary-art",
                       "medieval-art",
                       "neoclassical-art",
                       "prehistoric-art"]
        },
        "dance": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/dance/{}/",
            "topics": ["choreography",
                       "history-of-dance"]
        },
        "english": {
            "link": "https://quizlet.com/gb/topic/english/dance/{}/",
            "topics": ["linguistics",
                       "literature",
                       "vocabulary"]
        },
        "film and tv": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/film-and-tv/{}/",
            "topics": ["animation",
                       "film-criticism",
                       "film-theory",
                       "filmmaking",
                       "live-action"]
        },
        "history": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/history/{}/",
            "topics": ["ancient-history",
                       "history-of-the-environment",
                       "history-of-africa",
                       "history-of-asia",
                       "history-of-australia",
                       "history-of-europe",
                       "history-of-iran",
                       "history-of-russia",
                       "history-of-the-americas",
                       "intellectual-history",
                       "military-history",
                       "modern-history",
                       "scientific-history",
                       "technological-history",
                       "urban-history",
                       "western-civilization"]
        },
        "music": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/music/{}/",
            "topics": ["accompanying",
                       "chamber-music",
                       "church-music",
                       "conducting",
                       "early-music",
                       "ethnomusicology",
                       "jazz-studies",
                       "music-composition",
                       "music-education",
                       "music-history",
                       "music-theory",
                       "musicology",
                       "organology",
                       "recording"]
        },
        "philosophy": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/philosophy/{}/",
            "topics": ["applied-philosophy",
                       "ethics",
                       "history-of-philosophy",
                       "logic",
                       "metaphysics",
                       "social-and-political-philosophy",
                       "theology"]
        },
        "theatre": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/theatre/{}/",
            "topics": ["acting",
                       "directing",
                       "dramaturgy",
                       "history-of-theater",
                       "musical-theater",
                       "puppetry",
                       "stage-design"]
        },
        "visual arts": {
            "link": "https://quizlet.com/gb/topic/arts-and-humanities/visual-arts/{}/",
            "topics": ["architecture",
                       "calligraphy",
                       "decorative-arts",
                       "drawing",
                       "fashion-design",
                       "game-design",
                       "graphic-design",
                       "mixed-media",
                       "painting",
                       "photography",
                       "printmaking",
                       "product-design",
                       "sculpture",
                       "studio-art",
                       "textile-design",
                       "typography",
                       "user-experience-design"]
        }
    },

    "language": {
        "french": {
            "link": "https://quizlet.com/gb/topic/languages/french/{}/",
            "topics": ["activities",
                       "adjectives",
                       "adverbs",
                       "animals",
                       "body-parts",
                       "classroom",
                       "clothing",
                       "colors",
                       "conjunctions",
                       "current-events",
                       "expressions",
                       "feelings-and-emotions",
                       "food-and-dining",
                       "greetings",
                       "health",
                       "home",
                       "nature-and-the-environment",
                       "numbers",
                       "past-participles",
                       "places",
                       "prepositions",
                       "professions",
                       "questions",
                       "science-and-technology",
                       "shopping",
                       "social-relationships",
                       "sports",
                       "tenses",
                       "time",
                       "verbs",
                       "vocabulary",
                       "weather-and-seasons"]
        },
        "german": {
            "link": "https://quizlet.com/gb/topic/languages/german/{}/",
            "topics": ["activities",
                       "adjectives",
                       "adverbs",
                       "animals",
                       "body-parts",
                       "classroom",
                       "clothing",
                       "colors",
                       "conjunctions",
                       "current-events",
                       "expressions",
                       "feelings-and-emotions",
                       "food-and-dining",
                       "greetings",
                       "health",
                       "home",
                       "nature-and-the-environment",
                       "numbers",
                       "past-participles",
                       "places",
                       "prepositions",
                       "professions",
                       "questions",
                       "science-and-technology",
                       "shopping",
                       "social-relationships",
                       "sports",
                       "tenses",
                       "time",
                       "verbs",
                       "vocabulary",
                       "weather-and-seasons"]
        },
        "spanish": {
            "link": "https://quizlet.com/gb/topic/languages/spanish/{}/",
            "topics": ["activities",
                       "adjectives",
                       "adverbs",
                       "animals",
                       "body-parts",
                       "classroom",
                       "clothing",
                       "colors",
                       "conjunctions",
                       "current-events",
                       "expressions",
                       "feelings-and-emotions",
                       "food-and-dining",
                       "greetings",
                       "health",
                       "home",
                       "nature-and-the-environment",
                       "numbers",
                       "past-participles",
                       "places",
                       "prepositions",
                       "professions",
                       "questions",
                       "science-and-technology",
                       "shopping",
                       "social-relationships",
                       "sports",
                       "tenses",
                       "time",
                       "verbs",
                       "vocabulary",
                       "weather-and-seasons"]
        },
        "latin": {
            "link": "https://quizlet.com/gb/topic/languages/latin/{}/",
            "topics": ["activities",
                       "adjectives",
                       "adverbs",
                       "animals",
                       "body-parts",
                       "classroom",
                       "clothing",
                       "colors",
                       "conjunctions",
                       "current-events",
                       "expressions",
                       "feelings-and-emotions",
                       "food-and-dining",
                       "greetings",
                       "health",
                       "home",
                       "nature-and-the-environment",
                       "numbers",
                       "past-participles",
                       "places",
                       "prepositions",
                       "professions",
                       "questions",
                       "science-and-technology",
                       "shopping",
                       "social-relationships",
                       "sports",
                       "tenses",
                       "time",
                       "verbs",
                       "vocabulary",
                       "weather-and-seasons"]
        },
    },

    "social science": {
        "anthropology": {
            "link": "https://quizlet.com/gb/topic/social-science/anthropology/{}/",
            "topics": ["archaeology",
                       "biological-anthropology",
                       "cultural-anthropology",
                       "linguistic-anthropology",
                       "social-anthropology"]
        },
        "business": {
            "link": "https://quizlet.com/gb/topic/social-science/business/{}/",
            "topics": ["advertising",
                       "insurance",
                       "international-marketing",
                       "marketing-research",
                       "sports-marketing"]
        },
        "economics": {
            "link": "https://quizlet.com/gb/topic/social-science/economics/{}/",
            "topics": ["agricultural-economics",
                       "applied-economics",
                       "behavioural-economics",
                       "consumer-economics",
                       "development-economics",
                       "ecological-economics",
                       "econometrics",
                       "energy-economics",
                       "environmental-economics",
                       "finance",
                       "growth-economics",
                       "industrial-organisation",
                       "information-economics",
                       "international-economics",
                       "labour-economics",
                       "law-and-economics",
                       "macroeconomics",
                       "managerial-economics",
                       "microeconomics",
                       "monetary-economics",
                       "neuroeconomics",
                       "public-economics",
                       "real-estate-economics",
                       "resource-economics",
                       "transport-economics",
                       "welfare-economics"]
        },
        "human geography": {
            "link": "https://quizlet.com/gb/topic/social-science/human-geogrpahy/{}/",
            "topics": ["cultural-geography",
                       "development-geography",
                       "health-geography",
                       "historical-geography",
                       "language-geography",
                       "political-geography",
                       "population-geography",
                       "religion-geography",
                       "social-geography",
                       "tourism-geography",
                       "urban-geography"]
        },
        "law": {
            "link": "https://quizlet.com/gb/topic/social-science/law/{}/",
            "topics": ["administrative-law",
                       "canonic-law",
                       "civil-law",
                       "comparative-law",
                       "competition-law",
                       "constitutional-law",
                       "criminal-law",
                       "history-of-law",
                       "jewish-law",
                       "legal-management",
                       "procedural-law",
                       "public-law",
                       "substantive-law"]
        },
        "political science": {
            "link": "https://quizlet.com/gb/topic/social-science/political-science/{}/",
            "topics": ["politics-of-canada",
                       "civics",
                       "colonialism",
                       "comparative-politics",
                       "european-studies",
                       "geopolitics",
                       "imperialism",
                       "international-organisations",
                       "international-relations",
                       "political-behaviour",
                       "political-culture",
                       "political-economy",
                       "political-history",
                       "political-philosophy",
                       "politics-of-the-united-states",
                       "public-policy",
                       "voting-behaviour"]
        },
        "psychology": {
            "link": "https://quizlet.com/gb/topic/social-science/psychology/{}/",
            "topics": ["abnormal-psychology",
                       "applied-psychology",
                       "biological-psychology",
                       "clinical-neuropsychology",
                       "clinical-psychology",
                       "cognitive-psychology",
                       "community-psychology",
                       "comparative-psychology",
                       "consumer-psychology",
                       "counseling-psychology",
                       "criminal-psychology",
                       "cultural-psychology",
                       "developmental-psychology",
                       "educational-psychology",
                       "environmental-psychology",
                       "ergonomics",
                       "evolutionary-psychology",
                       "experimental-psychology,"
                       "family-psychology",
                       "forensic-psychology",
                       "group-psychology",
                       "health-psychology",
                       "humanistic-psychology",
                       "indigenous-psychology",
                       "legal-psychology",
                       "media-psychology",
                       "medical-psychology",
                       "music-psychology",
                       "neuropsychology",
                       "occupational-psychology",
                       "organizational-psychology",
                       "parapsychology,"
                       "paediatric-psychology",
                       "personality-psychology",
                       "phenomenology",
                       "political-psychology",
                       "positive-psychology",
                       "psychoanalysis",
                       "psychobiology",
                       "psychology-of-religion",
                       "psychometrics",
                       "psychopathology",
                       "psychophysics",
                       "quantitative-psychology",
                       "school-psychology",
                       "social-psychology",
                       "sport-psychology"]
        },
        "sociology": {
            "link": "https://quizlet.com/gb/topic/social-science/sociology/{}/",
            "topics": ["african-studies",
                       "applied-sociology",
                       "asian-studies",
                       "collective-behaviour",
                       "conflict-theory",
                       "criminology",
                       "cultural-sociology",
                       "environmental-sociology",
                       "ethnic-studies",
                       "gender-studies",
                       "immigration",
                       "interactionism",
                       "management",
                       "medical-sociology",
                       "middle-eastern-studies"
                       "north-american-studies",
                       "sexology",
                       "social-policy",
                       "social-theory",
                       "social-transformation",
                       "sociobiology",
                       "sociology-of-aging",
                       "sociology-of-religion",
                       "sociology-of-terrorism",
                       "sociology-of-the-body",
                       "sociology-of-the-family",
                       "urban-studies",
                       "victimology"]
        },
        "world geography": {
            "link": "https://quizlet.com/gb/topic/social-science/world-geography/{}/",
            "topics": ["geography-of-africa",
                       "geography-of-asia",
                       "geography-of-australia",
                       "geography-of-central-america",
                       "geography-of-europe",
                       "geography-of-north-america",
                       "geography-of-south-america",
                       "world-capitals"]
        }
    }
}